settings:
  username: IsmaellHV
  commit_username: github-actions[bot]
  commit_email: github-actions[bot]@users.noreply.github.com
  commit_message: ':zap: Update README with the recent activity'
  max_lines: 5
  readme_file: README.md
  disabled_events:
    - comments
  date_format: default
  timezone: UTC

recent_activity:
  - type: push
    emoji: 'â¬†ï¸'
    prefix: 'Pushed'
    suffix: 'commit(s) to'
  - type: issues
    emoji: 'ğŸ”¥'
    prefix: 'Opened issue'
    suffix: 'in'
  - type: pull_request
    emoji: 'ğŸ’ª'
    prefix: 'Opened PR'
    suffix: 'in'
  - type: pull_request_review
    emoji: 'ğŸ‘€'
    prefix: 'Reviewed PR'
    suffix: 'in'
  - type: create
    emoji: 'ğŸ‰'
    prefix: 'Created'
    suffix: ''
  - type: fork
    emoji: 'ğŸ´'
    prefix: 'Forked'
    suffix: ''
  - type: watch
    emoji: 'â­'
    prefix: 'Starred'
    suffix: ''
  - type: release
    emoji: 'ğŸš€'
    prefix: 'Released'
    suffix: 'in'
